title: Chaotic Notes
author.name: Krzysztof Banasik

description: >
 A bunch of write-ups, guides and thoughts on software engineering. Enjoy your stay!

show_excerpts: false

social_links.github: krisbanas

theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
